"use client";

import React, { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ShieldCheck, ArrowRight, Key, AlertCircle } from "lucide-react";

export default function TwoFactorAuthPage() {
  const router = useRouter();
  const [code, setCode] = useState("");
  const [useBackup, setUseBackup] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleVerify = (e: React.FormEvent) => {
    e.preventDefault();
    if (!code.trim()) return;

    setLoading(true);
    setError(null);

    // Simulation of TOTP verification
    setTimeout(() => {
      setLoading(false);
      // Valid code simulation
      if (code.length >= 6) {
        router.push("/app/dashboard");
      } else {
        setError("Invalid authentication code. Please check your authenticator app.");
      }
    }, 600);
  };

  return (
    <div className="min-h-screen bg-slate-50 dark:bg-[#090d16] flex flex-col justify-center py-12 sm:px-6 lg:px-8">
      <div className="sm:mx-auto sm:w-full sm:max-w-md px-4">
        <div className="bg-white dark:bg-slate-900 py-8 px-6 shadow-xl border border-slate-200 dark:border-slate-800 rounded-2xl text-center sm:px-10">
          <div className="w-12 h-12 rounded-xl bg-blue-100 dark:bg-blue-900/30 text-blue-600 flex items-center justify-center mx-auto mb-4">
            <ShieldCheck className="w-6 h-6" />
          </div>

          <h2 className="text-xl font-bold text-slate-900 dark:text-white">
            Two-Factor Authentication
          </h2>
          <p className="mt-1 text-xs text-slate-500">
            {useBackup
              ? "Enter one of your 8-digit emergency backup recovery codes."
              : "Enter the 6-digit TOTP code generated by Google Authenticator or 1Password."}
          </p>

          {error && (
            <div className="mt-4 p-3 rounded-xl bg-red-50 dark:bg-red-950/40 border border-red-200 dark:border-red-800/50 flex items-center gap-2 text-xs text-red-700 dark:text-red-400 text-left">
              <AlertCircle className="w-4 h-4 shrink-0" />
              <span>{error}</span>
            </div>
          )}

          <form onSubmit={handleVerify} className="mt-6 space-y-4">
            <div>
              <input
                type="text"
                required
                maxLength={useBackup ? 12 : 6}
                value={code}
                onChange={(e) => setCode(e.target.value.trim())}
                placeholder={useBackup ? "e.g. ABCD-1234" : "123456"}
                className="w-full text-center tracking-widest font-mono text-xl py-2.5 rounded-xl border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-800 text-slate-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-blue-500"
              />
            </div>

            <button
              type="submit"
              disabled={loading}
              className="w-full py-2.5 rounded-xl bg-blue-600 hover:bg-blue-700 text-white font-semibold text-xs transition-colors flex items-center justify-center gap-2 shadow-md disabled:opacity-50"
            >
              {loading ? "Verifying..." : "Verify & Continue"}
              <ArrowRight className="w-3.5 h-3.5" />
            </button>
          </form>

          <div className="mt-6 pt-6 border-t border-slate-100 dark:border-slate-800 flex items-center justify-between text-xs">
            <button
              onClick={() => {
                setUseBackup(!useBackup);
                setCode("");
                setError(null);
              }}
              className="text-blue-600 dark:text-blue-400 hover:underline font-medium"
            >
              {useBackup ? "Use Authenticator App" : "Use Backup Code"}
            </button>
            <Link href="/auth/login" className="text-slate-500 hover:text-slate-700 dark:hover:text-slate-300">
              Sign In with another account
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}
